encoding:     "utf-8"

# Site settings
title: "Andr&#233; Ruivo's blog"
email: avruivo@gmail.com
description: "This is a techy blog, with some programming/technical approaches and difficulties that I have experienced."
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
 
# Color settings (hex-codes without the leading hash-tag)
#	primary:   		#main + linkColors
#	secondary: 		#header bg + footer bg + h1.onAlternate
#	secondary-dark: #copyRight

# check https://color.adobe.com/my/themes/
color:
  primary: 433e3d
  secondary: 362e2d
  secondary-dark: 474a59
  alternate: 7e7e8e
  light: b4bcde

colorA:
  primary: 362e2d
  secondary: 433e3d
  secondary-dark: 474a59
  alternate: 7e7e8e
  light: b4bcde
  
colorB:
  primary: 433e3d
  secondary: 474a59
  secondary-dark: 7e7e8e
  alternate: b4bcde
  light: 362e2d
  
colorC:
  primary: 474a59
  secondary: 7e7e8e
  secondary-dark: b4bcde
  alternate: 362e2d
  light: 433e3d
  
colorD:
  primary: 7e7e8e
  secondary: b4bcde
  secondary-dark: 362e2d
  alternate: 433e3d
  light: 474a59
  
colorE:
  primary: b4bcde
  secondary: 362e2d
  secondary-dark: 433e3d
  alternate: 474a59
  light: 7e7e8e

# Owner/author information
owner:
  name:           Andre Ruivo
  avatar:         hmfaysal.jpg
  email:          hmfaysal@alum.mit.edu
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Awesome Dude, Awesome Life
  # Social networking links used in footer. Update and remove as you like.
  twitter:        andrevruivo
  #facebook:       hmfaysal
  github:         avruivo      
  #instagram:      hmfaysal
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:    https://plus.google.com/u/0/102602916593522619858
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/andrevruivo
  - title: linkedin
    url: http://linkedin.com/avruivo
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket 
    #url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/avruivo

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
#baseurl: /blog
exclude: ["README.md"]
